### ISSUE TITLE
AttributeError: 'openvino.inference_engine.ie_api.IENetwork' object has no attribute 'layers'

### ISSUE THREAD

**Issue by jomoengineer** [AhsanShihab/openvino-basic-app#1]
Hi Ahsan,
I enjoy your blogs with OpenVINO.

I attempted to run your 'openvino-basic-app' example and I receive the following error:

>  python3 app.py 
/home/jomodroid/develop/OpenVINO/examples/openvino-basic-app-master/inference.py:13: DeprecationWarning: Reading network using constructor is deprecated. Please, use IECore.read_network() method instead
  net = IENetwork(model=model, weights = model_bin)
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "app.py", line 44, in <module>
    main()
  File "app.py", line 9, in main
    exec_net = load_to_IE(model)
  File "/home/jomodroid/develop/OpenVINO/examples/openvino-basic-app-master/inference.py", line 17, in load_to_IE
    network_layers = net.layers.keys()
AttributeError: 'openvino.inference_engine.ie_api.IENetwork' object has no attribute 'layers'

According to the OpenVINO folks, ie_api.IENetwork has been removed from OpenVINO 2021.2 release and it is suggested to replace this with "get_ops()/get_ordered_ops() methods from nGraph Python API "
[https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/openvino-inference-engine-ie-api-IENetwork-object-has-no/m-p/1246624](url)

Jon

**Comment by AhsanShihab** [comment]
Hi Jon,

Thanks for bringing this to my attention. Really appreciate it. I will
update the code and my blog post. Glad to hear you enjoyed my blog.

Best wishes,
Ahsan

**Comment by AhsanShihab** [comment]
I have updated the code for OpenVINO 2021 version. Since OpenVINO 2020 version, we no longer need to check for unsupported layers. Sorry for the delay by the way.
